name: "Get and Cache dependencies"
description: "Get the dependencies via pnpm and cache item"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: Install dependencies
      if: ${{steps.cache-node-modules.outputs.cache-hit != 'true'}}
      run: pnpm install
      shell: bash #extra step
