name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v5
      - name: load & cache dependencies
        uses: ./.github/actions/cache-deps
      - name: lint the project
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone Project
        uses: actions/checkout@v5
      - name: load & cache dependencies
        uses: ./github/actions/cache-deps
      - name: lint the project
        run: pnpm run build
